### ISSUE TITLE
Bài #00: Hướng dẫn cài đặt môi trường với trình quản lý package Chocolate

### ISSUE THREAD

**Issue by vuthelinh** [vuthelinh/serenity-junit#1]
- Hệ điều hành Windows: Giờ đây mọi thứ sẽ đơn giản hơn không còn phải tìm để tải sau đó chạy cài đặt, thiết lập biến môi trường lằng nhằng nữa.

Tất cả chỉ trong một bước với Chocolate :
[Video hướng dẫn - Setup Java and Maven Environment](https://www.youtube.com/watch?v=yUXdDXBbRRI&list=PLpTCO0Fa9GR38qJ-AtT0EWJf5mDP7CXwJ&index=1)

Tham khảo thêm trên [blog](http://asksqa.blogspot.com/2019/06/bai-2-cai-at-moi-truong-va-cong-tac.html)

**Comment by Jacobvu84** [comment]
Lệnh cài java
`choco install jdk8 `

Lệnh cài maven
`choco install maven `

Lệnh cài eclipse
`choco install eclipse `

Ngoài ra muốn cài gì thêm vào mục  [packages](https://chocolatey.org/packages) search tên package muốn cài đặt để có được lệnh cài

**Comment by Jacobvu84** [comment]
Thảm khảo thêm các kiến thức cơ bản về git cho người mới bắt đầu [ở đây](https://github.com/Jacobvu84/Automated-Software-Testing/issues/6)

**Comment by Jacobvu84** [comment]
# Install JAVA JDK 8 (Java SE Development Kit)
* Open CMD and check java version: `c:\> java -version`
	* If the version is less than 1.8 or the command is not recognized you need to install java.
	* If the version is 1.8 or greater then go to Ruby install.
* Click [here](http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html)
* Select the Accept License Agreement radio button.
* Click the "jdk-8u231-windows-x64.exe" link for 64-bit machine.
* Click the "jdk-8u231-windows-i586.exe" link for 32-bit machine. 
* Make note of the installation/destination path! You will need this later. e.g. `C:\Program Files\Java\jdk1.8.0_xx`

### Add Environment Variables
* Goto Control Panel\System and Security\System > Advanced system.
* Add JAVA_HOME variable.
	* Click the New... button.
	* Set name: JAVA_HOME
	* Set value: C:\Program Files\Java\jdk1.8.0_xx
	* Click OK
* See example [here](https://www.dropbox.com/s/i9bncj8rni886mb/Environment%20Variables.PNG?dl=0) for environment variable.
* See example [here](https://www.dropbox.com/s/4nmzg085h907ub3/User%20Path%20Env%20Variables.PNG?dl=0) for Path variables.
* Close all CMD's and **RESTART PC!**

### Test Environment Variables
* Run `C:\> java -version` in CMD. You should see something close to this `java version "1.8.0_231"` or greater returned.

### Install Eclipse 
* Download and install [eclipse](https://www.eclipse.org/downloads/)

**Comment by Jacobvu84** [comment]
- [Installing Apache Maven on Windows](https://docs.wso2.com/display/IS323/Installing+Apache+Maven+on+Windows)
