### ISSUE TITLE
Bài #11: Tìm kiếm các đối tượng sử dụng Xpath Axes

### ISSUE THREAD

**Issue by vuthelinh** [vuthelinh/serenity-junit#11]
Cách cách tìm kiếm đối tượng đươc support bởi Serenity và cách tương tác với đối tượng sau khi tìm thấy 

[Video hướng dẫn](https://www.youtube.com/watch?v=JniC54fhCrA&list=PLpTCO0Fa9GR38qJ-AtT0EWJf5mDP7CXwJ&index=12)

**Comment by vuthelinh** [comment]
[Video - xpath ](https://www.youtube.com/playlist?list=PLpTCO0Fa9GR3QfiFocwoj0Gvu-o16YBDa)

**Comment by Jacobvu84** [comment]
Tham khảo thêm https://github.com/Jacobvu84/serenity-pageobject-junit-webdriver/issues/42

**Comment by Jacobvu84** [comment]
https://github.com/Jacobvu84/serenity-pageobject-junit-webdriver/issues/56
