### ISSUE TITLE
Bài #19: Timeouts và Waits ( Implicit Explicit )

### ISSUE THREAD

**Issue by vuthelinh** [vuthelinh/serenity-junit#19]
- `webdriver.timeouts.implicitlywait` is used for most implicit waits

 Chờ ngầm sẽ báo cho trình điều khiển web chờ trong khoảng thời gian xác định trước khi nó hết kiên nhẫn và đưa ra thông báo “No Such Element Exception”.
`driver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);`

Use `setImplicitTimeout()` to change.

- `webdriver.wait.for.timeout` is the default timeout used in the Serenity wait() methods, if an explicit timeout isn't specified. (Explicit Wait)

Use `setWaitForTimeout()` to set timeouts

`withTimeoutOf(20, SECONDS).find("does-not-exist");`

**Comment by vuthelinh** [comment]
``` 
WebElementFacade elem = withTimeoutOf(Duration.ofSeconds(5)).waitFor(By.xpath("xxx"));
```

**Comment by vuthelinh** [comment]
[Video hướng dẫn](https://www.youtube.com/watch?v=e59BCPqiKj0&feature=youtu.be)

**Comment by vuthelinh** [comment]
```
        @FindBy(id = "textBox")
        public WebElementFacade textbox;

        public void waitAndClick() {
            buttonThatIsEnabledLater.withTimeoutOf(Duration.ofSeconds(10)).click();
        }
```

**Comment by vuthelinh** [comment]
```
        public WebElementFacade waitUntilVisibleButton() {
            return withTimeoutOf(Duration.ofSeconds(10))
                    .find(By.id("eventually-visible-button"));
        }
```

**Comment by vuthelinh** [comment]
```
        public void waitForVisibleTextToAppear() {
            waitForCondition().until(
                    ExpectedConditions.textToBePresentInElement(textbox, "Visible text")
            );
        }
```

**Comment by vuthelinh** [comment]
```
    @Test
    public void waitingForVisibleTextExpectedCondition() {
        pageWithWaits.waitForCondition()
                .until(
                        ExpectedConditions.numberOfElementsToBe(
                                By.cssSelector("#elements option"), 4
                        )
                );
    }
```

**Comment by vuthelinh** [comment]
lấy số lượng các option trong thẻ select
```
        public List<String> displayedElements() {
            return findAll("#elements option")
                    .stream()
                    .map(WebElementFacade::getText)
                    .collect(Collectors.toList());
        }
```

**Comment by vuthelinh** [comment]
Khi cần kiểm soát thời gian chờ chi tiết hơn, bạn có thể xác định thời gian chờ trực tiếp trong mã của mình, sử dụng phương thức `withTimeoutOf ()`. Trong bất kỳ PageObject hoặc Action class  nào, bạn có thể sử dụng phương pháp này để ghi đè thời gian chờ Fluent Wait:
```
public void clickOnButtonThatWillEventuallyAppear() {
      withTimeoutOf(Duration.ofSeconds(30))
                  .find(By.id("eventually-visible-button"))
                  .click()
}
```

**Comment by Thuhuong-1988** [comment]
Anh ơi, em đã thử hết những gợi ý của a mà vẫn k fix đc lỗi no such element: Unable to locate element. Anh xem giúp em với ạ
Trường hợp em cần lấy là product: 
![image](https://user-images.githubusercontent.com/37929864/72250880-4065d600-362f-11ea-8c04-06d154bd1360.png)

**Comment by Jacobvu84** [comment]
@Thuhuong-1988 e là học sinh của anh thì liên hệ qua skype
