### ISSUE TITLE
Bài #02: Thiết lập cấu hình để chạy thử dự án mẫu

### ISSUE THREAD

**Issue by vuthelinh** [vuthelinh/serenity-junit#3]
- Tìm và tải các driver cho các trình duyệt
- Thiết lập biến hệ thống

[video hướng dẫn](https://www.youtube.com/watch?v=uobNGqeZq7c&list=PLpTCO0Fa9GR38qJ-AtT0EWJf5mDP7CXwJ&index=3)

**Comment by vuthelinh** [comment]
Bài học tiếp theo nên là https://github.com/vuthelinh/serenity-junit/issues/4

**Comment by Jacobvu84** [comment]
Nộp bài:

Sau khi học xong bài này học viên cần
- Update code lên repository của mình và gửi cho thầy kiểm tra. Sau khi review xong được approve mới được học bài tiếp theo.

Tóm tắt mục tiêu cần đặt được
- Thiết lâp geckodriver và chromedriver trong file cấu hình để chạy được dự án mẫu.

**Comment by Jacobvu84** [comment]
[Kiểm tra tương thích version](https://www.youtube.com/watch?v=u2VlMg5h3pM&list=PLpTCO0Fa9GR1Wq7BW_MpR9ttm3Fl0s2Ik&index=3)
