### ISSUE TITLE
Bài #04: Phân tích các thông số mặc định trong file serenity.properties 

### ISSUE THREAD

**Issue by vuthelinh** [vuthelinh/serenity-junit#5]
[Video hướng dẫn ](https://www.youtube.com/watch?v=ZRguRMDdRoA&list=PLpTCO0Fa9GR38qJ-AtT0EWJf5mDP7CXwJ&index=5)

**Comment by Jacobvu84** [comment]
Xem thêm các properties khác ở đây

http://thucydides.info/docs/serenity-staging/#_serenity_system_properties_and_configuration
