### ISSUE TITLE
Bài #06: Phân tích cấu trúc dự án theo mô hình Page Object Model  

### ISSUE THREAD

**Issue by vuthelinh** [vuthelinh/serenity-junit#7]
[Video hướng dẫn](https://www.youtube.com/watch?v=MQfU-03RPqs&list=PLpTCO0Fa9GR38qJ-AtT0EWJf5mDP7CXwJ&index=7)

**Comment by Jacobvu84** [comment]
Học sinh cần nắm: Trong mô hình page object có mấy phần và chức năng của từng phần.
