### ISSUE TITLE
Bài #07: Làm sao để mở ứng dụng web trên browser với serenity 

### ISSUE THREAD

**Issue by vuthelinh** [vuthelinh/serenity-junit#8]
[Video hướng dẫn](https://www.youtube.com/watch?v=b2TTf6taaq0&list=PLpTCO0Fa9GR38qJ-AtT0EWJf5mDP7CXwJ&index=8)

**Comment by Jacobvu84** [comment]
Kiến thức cần nắm. Cách thức kế thừa class để sử dụng các method trong bộ core của framework.

Tại bài này có thể mở rộng việc học 1 trong 4 tính chất của OOP là Kết thừa ( inheritance).

Học sinh cần phải viết một thêm 2 classes và kế thừa nhau. Sau đó trả lời một số câu hỏi liên quan tới tính kế thừa.

Các câu hỏi sẽ được gửi vào mail cho các học viên đã hoàn thành bài số 7

**Comment by Jacobvu84** [comment]
một vài [lệnh git cơ bản](https://www.youtube.com/watch?v=2jtHjpIJ7VI&list=PLpTCO0Fa9GR1Wq7BW_MpR9ttm3Fl0s2Ik&index=5)
